services:
  ssh:
    container_name: sample-cicd-api-ssh
    image: local-ssh-server
    privileged: true
    ports:
      - 22:22
      - 3000:3000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - sample-cicd-api
  jenkins:
    container_name: sample-cicd-api-jenkins
    image: jenkins/jenkins
    privileged: true
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - jenkins_vol:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - sample-cicd-api

volumes:
  jenkins_vol:

networks:
  sample-cicd-api:
    driver: bridge